import { Loading } from './Loading'

export { TextInput }  from './Input'
export { InputLogin }  from './InputLogin'
export { HeaderNavigation } from './Switch'
// export { Button } from './Button'
export { TextFooter } from './TextFooter'
export { ListNotice } from './ListNotice'
export { ListLive } from './ListLive'
export { List2Live } from './List2Live'
export { ListCursos } from './ListCursos'
export { ListVideos } from './ListVideos'
export { ListComentarios } from './ListComentarios'
// export Donut from './ProgressCircle'
export { Loading } from './Loading'